---

# Follows the guide
# https://ostechnix.com/how-to-migrate-to-centos-stream-8-from-centos-linux-8/

- hosts: all
  become: true
  tasks:
    - name: fail early if os is not centos 8
      assert:
        that: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8'

    - name: upgrade all packages
      dnf:
        name: '*'
        state: latest

    - name: install centos-release-stream
      package:
        state: present
        name: centos-release-stream

    - name: switch to stream
      command:
        cmd: dnf swap centos-linux-repos centos-stream-repos -y
        warn: false

    - name: sync distro
      command:
        cmd: dnf distro-sync -y
        warn: false

    - name: reboot the system
      reboot:
